#!/bin/bash

# Check if the correct number of arguments is provided
if [ $# -ne 1 ]; then
    cat << EOF
Usage: $0 [bridge name]

Creates a bridge and sets it's status to up.
Removes on exit.

Example:
  $0 veth0

Requires su permissions.
EOF
    exit 1
fi

bridge_name=$1

if ip link show $bridge_name > /dev/null 2>&1; then
    echo "Link with name $bridge_name already exists."
    exit 1
fi

sudo ip link add name $bridge_name type bridge
sudo ip link set dev $bridge_name up

# Function to clean up virtual interface
cleanup() {
    # Remove the virtual interface
    sudo ip link delete $bridge_name
}


# Trap to call cleanup function on exit
trap cleanup EXIT

# Infinite loop
while true; do
    sleep 1  # Sleep for a second to prevent high CPU usage
done

