#!/bin/bash

# Check if the correct number of arguments is provided
if [ $# -ne 1 ]; then
    cat << EOF
Usage: $0 [virtual interface name]

Creates a virtual interface and sets it's status to up.
Removes on exit.

Example:
  $0 veth0

Requires su permissions.
EOF
    exit 1
fi

# virtual interface name
v_if_name=$1

if ip link show $v_if_name > /dev/null 2>&1; then
    echo "Interface $v_if_name already exists."
    exit 1
fi


sudo ip link add $v_if_name type dummy

# Function to clean up virtual interface
cleanup() {
    # Remove the virtual interface
    sudo ip link delete $v_if_name
}

sudo ip link set $v_if_name up


# Trap to call cleanup function on exit
trap cleanup EXIT

# Infinite loop
while true; do
    sleep 1  # Sleep for a second to prevent high CPU usage
done

