#!/bin/bash

# Check if the correct number of arguments is provided
if [ $# -ne 1 ]; then
    cat << EOF
Usage: $0 [bridge name]

Creates a bridge and sets it's status to up.
Removes on exit.

Example:
  $0 veth0

Requires su permissions.
EOF
    exit 1
fi

