/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_PRIMITIVE_CHANNELS_PB_H_INCLUDED
#define PB_PRIMITIVE_CHANNELS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Int32Array {
    pb_callback_t values;
} Int32Array;

typedef struct _FloatArray {
    pb_callback_t values;
} FloatArray;

typedef struct _DoubleArray {
    pb_callback_t values;
} DoubleArray;

typedef struct _PrimitiveChannels {
    pb_size_t which_value;
    union {
        Int32Array int_channels;
        FloatArray float_channels;
        DoubleArray double_channels;
    } value;
} PrimitiveChannels;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PrimitiveChannels_init_default           {0, {Int32Array_init_default}}
#define Int32Array_init_default                  {{{NULL}, NULL}}
#define FloatArray_init_default                  {{{NULL}, NULL}}
#define DoubleArray_init_default                 {{{NULL}, NULL}}
#define PrimitiveChannels_init_zero              {0, {Int32Array_init_zero}}
#define Int32Array_init_zero                     {{{NULL}, NULL}}
#define FloatArray_init_zero                     {{{NULL}, NULL}}
#define DoubleArray_init_zero                    {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Int32Array_values_tag                    1
#define FloatArray_values_tag                    1
#define DoubleArray_values_tag                   1
#define PrimitiveChannels_int_channels_tag       1
#define PrimitiveChannels_float_channels_tag     2
#define PrimitiveChannels_double_channels_tag    3

/* Struct field encoding specification for nanopb */
#define PrimitiveChannels_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,int_channels,value.int_channels),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,float_channels,value.float_channels),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,double_channels,value.double_channels),   3)
#define PrimitiveChannels_CALLBACK NULL
#define PrimitiveChannels_DEFAULT NULL
#define PrimitiveChannels_value_int_channels_MSGTYPE Int32Array
#define PrimitiveChannels_value_float_channels_MSGTYPE FloatArray
#define PrimitiveChannels_value_double_channels_MSGTYPE DoubleArray

#define Int32Array_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, INT32,    values,            1)
#define Int32Array_CALLBACK pb_default_field_callback
#define Int32Array_DEFAULT NULL

#define FloatArray_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FLOAT,    values,            1)
#define FloatArray_CALLBACK pb_default_field_callback
#define FloatArray_DEFAULT NULL

#define DoubleArray_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, DOUBLE,   values,            1)
#define DoubleArray_CALLBACK pb_default_field_callback
#define DoubleArray_DEFAULT NULL

extern const pb_msgdesc_t PrimitiveChannels_msg;
extern const pb_msgdesc_t Int32Array_msg;
extern const pb_msgdesc_t FloatArray_msg;
extern const pb_msgdesc_t DoubleArray_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PrimitiveChannels_fields &PrimitiveChannels_msg
#define Int32Array_fields &Int32Array_msg
#define FloatArray_fields &FloatArray_msg
#define DoubleArray_fields &DoubleArray_msg

/* Maximum encoded size of messages (where known) */
/* PrimitiveChannels_size depends on runtime parameters */
/* Int32Array_size depends on runtime parameters */
/* FloatArray_size depends on runtime parameters */
/* DoubleArray_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
