/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "segments.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(segments_Segment, segments_Segment, AUTO)


PB_BIND(segments_SegmentsFrame, segments_SegmentsFrame, AUTO)



