/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_RESPONSE_PB_H_INCLUDED
#define PB_RESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Primitive {
    pb_size_t which_value;
    union {
        int32_t int_val;
        int64_t long_val;
        float float_val;
        double double_val;
        bool bool_val;
        char string_val[61];
    } value;
} Primitive;

typedef struct _Response {
    char metric_id[41];
    bool has_primitive;
    Primitive primitive;
} Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Response_init_default                    {"", false, Primitive_init_default}
#define Primitive_init_default                   {0, {0}}
#define Response_init_zero                       {"", false, Primitive_init_zero}
#define Primitive_init_zero                      {0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define Primitive_int_val_tag                    1
#define Primitive_long_val_tag                   2
#define Primitive_float_val_tag                  3
#define Primitive_double_val_tag                 4
#define Primitive_bool_val_tag                   5
#define Primitive_string_val_tag                 6
#define Response_metric_id_tag                   1
#define Response_primitive_tag                   2

/* Struct field encoding specification for nanopb */
#define Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   metric_id,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  primitive,         2)
#define Response_CALLBACK NULL
#define Response_DEFAULT NULL
#define Response_primitive_MSGTYPE Primitive

#define Primitive_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_val,value.int_val),   1) \
X(a, STATIC,   ONEOF,    INT64,    (value,long_val,value.long_val),   2) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_val,value.float_val),   3) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_val,value.double_val),   4) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_val,value.bool_val),   5) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_val,value.string_val),   6)
#define Primitive_CALLBACK NULL
#define Primitive_DEFAULT NULL

extern const pb_msgdesc_t Response_msg;
extern const pb_msgdesc_t Primitive_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Response_fields &Response_msg
#define Primitive_fields &Primitive_msg

/* Maximum encoded size of messages (where known) */
#define Primitive_size                           62
#define RESPONSE_PB_H_MAX_SIZE                   Response_size
#define Response_size                            106

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
