# https://www.thisdot.co/blog/deploying-multiple-apps-from-a-monorepo-to-github-pages
# https://github.com/DenverCoder1/doxygen-github-pages-action
name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - json-telemetry

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          folder: onboard-telemetry-client/docs/html
          config_file: onboard-telemetry-client/Doxyfile
          github_token: ${{ secrets.GITHUB_TOKEN }}