#!/bin/bash

if [ -z "$1" ] || [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_nanopb>"
  exit 1
fi

ROOT_PATH="$(dirname "$0")"

cd $ROOT_PATH

python3 -m venv temp/temp_env

source temp/temp_env/bin/activate

echo "Installing nanopb_generator.py dependencies in temporary venv"

pip install protobuf grpcio-tools  # nanopb_generator.py dependencies

NANOPB_PATH=$1

echo $NANOPB_PATH

PROTO_PATH="$ROOT_PATH/sample.proto"

OUTPUT_DIR=./src/generated/nanopb

"$NANOPB_PATH/generator/nanopb_generator.py" --output-dir=$OUTPUT_DIR $PROTO_PATH

deactivate

rm -rf temp/temp_env
